server:
  port: 8085

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: products
          uri: lb://PRODUCTS
          predicates:
            - Path=/api/v1/products/**
        - id: sales
          uri: lb://SALES
          predicates:
            - Path=/api/v1/sales/**
        - id: billing
          uri: lb://BILLING
          predicates:
            - Path=/api/v1/Billing/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      fetch-registry: true
      register-with-eureka: true

