server:
  port: 8080
spring:
  application:
    name: products
  datasource:
    password: 'alper'
    url: jdbc:postgresql://localhost:5432/product
    username: 'alper'
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

